name: 'Setup Hashlink'
description: 'Install and setup Hashlink'
runs:
  - uses: actions/checkout@master
  - uses: seanmiddleditch/gha-setup-ninja@master
  - run: |
    mkdir build
    cd build
    cmake -G Ninja ..
  - run: cmake --build build
  using: 'node12'
  main: 'main.js'
branding:
  icon: 'download'
  color: 'gray-dark'
