on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest,windows-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: build Hashlink
        uses: './'

      - name: build test
        uses: 'haxe -main Test -hl test.hl'
      - name: run test
        uses: 'hl test.hl'