name: CI

on: [push,pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - uses: actions/setup-node@v1
      - name: install lix
        run: npm i lix -g
      - name: run lix
        run: npx lix download
      - name: build test
        run: npx haxe test.hxml
      - name: run test
        run: hl test.hl
